# Generated by Django 5.0.4 on 2024-04-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_vendor_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(default='Raipur', max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
