# Generated by Django 5.0.4 on 2024-05-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_vendor_user_alter_historicalpurchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
    ]
